DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	Id INT NOT NULL AUTO_INCREMENT,
	UserName VARCHAR(255),
	Password VARCHAR(255),
	ImageLocation VARCHAR(255),
	FirstName VARCHAR(255),
	LastName VARCHAR(255),
	DateOfBirth DATE,
	
	PRIMARY KEY (Id)
);