# -*- mode: ruby -*-
# vi: set ft=ruby :

server_ip="192.168.50.4"

database_username="Player_1"
database_password="Player_2"


Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.synced_folder ".", "/vagrant", :disabled => true
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 1
	end
	
	
	config.vm.provision :shell, :path => "Scripts/Docker.sh"
	#config.vm.provision :shell, :path => "Scripts/Config-localhost.sh"
	
	#config.vm.define :Watchdog do |wd|
		#wd.vm.provision :shell, :path => "Scripts/Consul-server.sh"
		
		#wd.vm.network :private_network, :ip => server_ip
	#end
	
	config.vm.define :Database do |db|
		db.vm.synced_folder "VMs/Database/Sql", "/home/Sql"
		db.vm.synced_folder "VMs/Database/Project", "/home/Project"
	
		db.vm.provision :shell, :path => "Scripts/Java-8-jdk.sh"
		db.vm.provision :shell, :path => "Scripts/Sbt.sh"
	
		#db.vm.provision :shell, :path => "Scripts/Consul-client.sh", :args => ["Database", server_ip]
		#db.vm.provision :shell, :path => "Scripts/Registrator.sh"

		db.vm.provision :shell, :path => "Scripts/Docker/MySql.sh", :args => [database_username, database_password]
		
		db.vm.network :private_network, :type => "dhcp"
	end

	#config.vm.define :Middleware do |mw|
		#mw.vm.synced_folder "VMs/Middleware/Project", "/home/Project"
		
		#mw.vm.provision :shell, :path => "Scripts/Consul-client.sh", :args => ["Middleware", server_ip]
		#mw.vm.provision :shell, :path => "Scripts/Java-11-jdk.sh"
		#mw.vm.provision :shell, :path => "Scripts/Sbt.sh"
		
		
		#mw.vm.provision :shell, :path => "VMs/Middleware/Bootstrap.sh"
		
		#mw.vm.network :private_network, :type => "dhcp"
	#end

	#config.vm.define :Webserver do |ws|
		#ws.vm.synced_folder "VMs/Webserver/Project", "/home/Project"
		
		#ws.vm.provision :shell, :path => "Scripts/Client.sh", :args => [server_ip, "Webserver"]
		#ws.vm.provision :shell, :path => "Scripts/Java-11-jdk.sh"
		#ws.vm.provision :shell, :path => "Scripts/Sbt.sh"
		
		#ws.vm.provision :shell, :path => "VMs/Webserver/Bootstrap.sh"
		
		#ws.vm.network :private_network, :type => "dhcp"
	#end
end